apiVersion: v1
kind: Service
metadata:
  name: {{ include "kmate-hub.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kmate-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "kmate-hub.selectorLabels" . | nindent 4 }}
  ports:
  - { name: http,    port: {{ .Values.service.clientPort }}, targetPort: http,    appProtocol: http }
  - { name: grpc,    port: {{ .Values.service.agentPort }},  targetPort: grpc,    appProtocol: grpc }
  - { name: metrics, port: {{ .Values.service.metricsPort }}, targetPort: metrics, appProtocol: http }
